{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.facompose",
    "module": "facompose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "facompose-1.0.0.aar",
          "url": "facompose-1.0.0.aar",
          "size": 402735,
          "sha512": "cdc62a54f685532e385cdc80292643d3d309051a33d39b0b2cf41d4bc6f0f8d322b9b38bc5a5681c81c5f1007ed2b2d2b1c3eb352687ae1eb09d0f84130e1b73",
          "sha256": "5c3319713e106508ed6beb3bc0997d8c71cab4176046fef799e5c861364ad493",
          "sha1": "16649a97c32c85e5e0b5e36c4d2f8470232b76fd",
          "md5": "b6d14077ccdaa4bdbb504b2b8c1e0273"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "facompose-1.0.0.aar",
          "url": "facompose-1.0.0.aar",
          "size": 402735,
          "sha512": "cdc62a54f685532e385cdc80292643d3d309051a33d39b0b2cf41d4bc6f0f8d322b9b38bc5a5681c81c5f1007ed2b2d2b1c3eb352687ae1eb09d0f84130e1b73",
          "sha256": "5c3319713e106508ed6beb3bc0997d8c71cab4176046fef799e5c861364ad493",
          "sha1": "16649a97c32c85e5e0b5e36c4d2f8470232b76fd",
          "md5": "b6d14077ccdaa4bdbb504b2b8c1e0273"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "facompose-1.0.0-sources.jar",
          "url": "facompose-1.0.0-sources.jar",
          "size": 6636,
          "sha512": "6c535bfb6a4d1ad44083990e4353b82e8212c2fcf9959140069b63528e138256044778dc2a31d9ff4a74cf4083d59793749a1cad271c46f7e4bdc4dcc2495c03",
          "sha256": "dba6ec6669f3e848f65e0bf42cc9fbad31f905735a23bb86f3354abfebb5b9af",
          "sha1": "f2b25094c3d1a35fbe50a63cd0ea0ab86d04427a",
          "md5": "6985023fcd7a111b751f3eda0601d37c"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.example.facompose",
          "module": "facompose",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "facompose-1.0.0-test-fixtures.aar",
          "url": "facompose-1.0.0-test-fixtures.aar",
          "size": 790,
          "sha512": "46807cadb8d59745a0125b012085e10a59a47d67c75793ff45557ee0dd467add719528af9eec2364a5f036326310b0d448599611e1625bf694509121883c5839",
          "sha256": "5e21d516351bba5cefb02a672639b853e37f8dd5c6f3fd6b69ece9cb527ad396",
          "sha1": "546931867b114312ec2ed4a2c9d21e463950e7ef",
          "md5": "2320dcaae610238b77fc7fd8de4aff54"
        }
      ],
      "capabilities": [
        {
          "group": "ComposeFADemo",
          "name": "facompose-test-fixtures",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.example.facompose",
          "module": "facompose",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "facompose-1.0.0-test-fixtures.aar",
          "url": "facompose-1.0.0-test-fixtures.aar",
          "size": 790,
          "sha512": "46807cadb8d59745a0125b012085e10a59a47d67c75793ff45557ee0dd467add719528af9eec2364a5f036326310b0d448599611e1625bf694509121883c5839",
          "sha256": "5e21d516351bba5cefb02a672639b853e37f8dd5c6f3fd6b69ece9cb527ad396",
          "sha1": "546931867b114312ec2ed4a2c9d21e463950e7ef",
          "md5": "2320dcaae610238b77fc7fd8de4aff54"
        }
      ],
      "capabilities": [
        {
          "group": "ComposeFADemo",
          "name": "facompose-test-fixtures",
          "version": "unspecified"
        }
      ]
    }
  ]
}
